### ISSUE TITLE
Username must be alpha numeric

### ISSUE THREAD

**Issue by rlaiola** [AryelleSiqueira/boca-auth#10]
Although the admin user can create new users containing all types of characters (up to 20), these receive a _Username must be alpha numeric_ message when trying to log in into the application.

<img width="1392" alt="Screen Shot 2023-09-19 at 09 03 59" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/aead1e61-5fbe-49f3-b614-d7f03459f2f7">

**Proposed solution:** Skip this validation at login (comment the code out) the same way as it is already for the admin user. This will bring flexibility and allow the use of BOCA in more scenarios (e.g., with user accounts containing `.`).

## How to reproduce this behavior?

- Edit the `docker-compose.yml` file accordingly:

```yaml
    ...
    boca-web:
        ...
        environment:
            ...
            - BOCA_AUTH_METHOD=password
            - BOCA_SYSTEM_USER=professorum
            - BOCA_ADMIN_USER=professordois
            ...
    ...
```

- Launch the application:

```sh
docker compose up --build
````

- Open a web browser and visit [http://localhost:8001/boca](http://localhost:8001/boca). Log in with the credentials of the user specified in the `BOCA_SYSTEM_USER` env variable (_professorum_). Then, create and activate a contest (via `Contest` menu);
- After being logged out, log in with the credentials of the user specified in the `BOCA_ADMIN_USER` env variable (_professordois_). Click on the `Users` menu, select the provided batch file ([BOCA_USERS.txt](https://github.com/AryelleSiqueira/boca-auth/files/12659774/BOCA_USERS.txt)) and click on the `Import` button. Three users should be created;
- Finally, try to log in with the credentials of one of these users (e.g., Name: _bruce.wayne_ / Password: _boca_);
- To stop the application:

```sh
docker compose down
````
