### ISSUE TITLE
Authentication not working for Google accounts

### ISSUE THREAD

**Issue by rlaiola** [AryelleSiqueira/boca-auth#13]
If `BOCA_AUTH_METHOD=google`, I was able to log in only if the env variables `BOCA_SYSTEM_USER` and `BOCA_ADMIN_USER` are set with the default values.

```yaml
    ...
    boca-web:
        ...
        environment:
            ....
            - BOCA_SYSTEM_USER=system
            - BOCA_ADMIN_USER=admin
            - BOCA_AUTH_METHOD=google
            # configuration options for Google authentication
            - AUTH_ALLOWED_DOMAINS=edu.ufes.br,ufes.br
            ...
    ...
```

If `BOCA_SYSTEM_USER` or `BOCA_ADMIN_USER` is set with my institutional or personal user account, the authentication process does not work (an alert pops up showing _User does not exist or incorrect password_ or _Usuário não autorizado._). The sample configuration follows:

```yaml
    ...
    boca-web:
        ...
        environment:
            ....
            - BOCA_SYSTEM_USER=system
            - BOCA_ADMIN_USER=MY_LOGIN_WITHOUT_AT_UFES.BR
            - BOCA_AUTH_METHOD=google
            # configuration options for Google authentication
            - AUTH_ALLOWED_DOMAINS=ufes.br
            ...
    ...

```
