### ISSUE TITLE
Admin password is incorrect

### ISSUE THREAD

**Issue by rlaiola** [AryelleSiqueira/boca-auth#22]
Considering the `docker-compose.yml` file as follows (branch `master`):

```yaml
    ...
    boca-web:
        ...
        environment:
            ....
            #- BOCA_SYSTEM_USER=system
            #- BOCA_ADMIN_USER=admin
            - BOCA_AUTH_METHOD=google
            # configuration options for Google authentication
            - BOCA_AUTH_ALLOWED_DOMAINS=edu.ufes.br,ufes.br
            ...
    ...
```

I logged in as `system`, created and activated a new contest. Then, I logged in as `admin` and tried to create a new user filling in the form.

![Screen Shot 2023-10-02 at 16 30 20](https://github.com/AryelleSiqueira/boca-auth/assets/4059310/90a0ae20-6a82-451b-a6ab-6a3182169f13)

![Screen Shot 2023-10-02 at 16 30 26](https://github.com/AryelleSiqueira/boca-auth/assets/4059310/388683dc-cc8c-46c0-92ad-37b44892a9f2)
