### ISSUE TITLE
UI shows wrong username and user full name when using LDAP authentication method

### ISSUE THREAD

**Issue by rlaiola** [AryelleSiqueira/boca-auth#6]
## How to reproduce this issue?

- Edit the `docker-compose.yml` file accordingly:

```yaml
    ...
    boca-web:
        ...
        environment:
            ...
            - BOCA_AUTH_METHOD=ldap
            - LDAP_SERVER=ldap://ldap:389
            - LDAP_BASE_DN=dc=inf,dc=ufes,dc=br
            - LDAP_USER=cn=admin,dc=inf,dc=ufes,dc=br
            - LDAP_PASSWORD=ldappw
            - BOCA_SYSTEM_USER=professorum
            - BOCA_ADMIN_USER=professordois
            ...
    ...
```

- Launch the application:

```sh
docker compose up --build
````

- Open a web browser and visit [http://localhost:8001/boca](http://localhost:8001/boca). Log in with the credentials of the user specified in the `BOCA_SYSTEM_USER` env variable (_professorum_). The issue appears in the first page;

<img width="1392" alt="Screen Shot 2023-09-18 at 23 23 39" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/53322161-8f47-4bb8-9251-ff28fae260cd">

- Clicking on the `Options` menu it seems that the user info has not been retrieved from the LDAP server:
<img width="1392" alt="Screen Shot 2023-09-18 at 23 26 53" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/187ac9a2-438a-4e6b-809e-7dad55d3a1ff">

- To stop the application

```sh
docker compose down
````

- The problem has also been noticed for the admin user (`BOCA_ADMIN_USER=professordois`);

<img width="1348" alt="Screen Shot 2023-09-18 at 23 50 43" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/d3a5055b-2a92-4b32-9905-4125a2cf648c">

<img width="1392" alt="Screen Shot 2023-09-18 at 23 51 18" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/74909778-7301-4dd0-9702-af2d48c9436b">

<img width="1392" alt="Screen Shot 2023-09-18 at 23 55 31" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/f809547b-93db-4e3a-9f8a-49e2246f6cfc">

- Idem for team members (e.g., _alunoum_ and _alunodois_);
