### ISSUE TITLE
Fallback for users not found in remote auth service (e.g., LDAP)

### ISSUE THREAD

**Issue by rlaiola** [AryelleSiqueira/boca-auth#7]
Right now, if a user is registered in BOCA but not found in the LDAP server (`BOCA_AUTH_METHOD=ldap`), the application shows an error message (_User not found in ldap server_). Perhaps, a way to define `password` as the fallback method could help making the application more flexible for more use cases.

**Proposed solution:**
- Try to authenticate using the specified method (e.g., `BOCA_AUTH_METHOD=ldap`);
- If authentication succeeds, then user is granted access to the application;
- Otherwise, 
    - if `BOCA_ENABLE_FALLBACK_AUTH=true` and the user was not found in the remote server, then try to authenticate using the `password` method against the BOCA database;
        - If authentication succeeds, then user is granted access to the application;
        - Otherwise, authentication fails;
     - Otherwise, authentication fails;

Below a sample file in which team users (_alunoum_ and _alunodois_) can be found in the provided LDAP server but the last (_alunotres_). 

[BOCA_USERS.txt](https://github.com/AryelleSiqueira/boca-auth/files/12658803/BOCA_USERS.txt)

## How to reproduce this behavior?

- Edit the `docker-compose.yml` file accordingly:

```yaml
    ...
    boca-web:
        ...
        environment:
            ...
            - BOCA_AUTH_METHOD=ldap
            - LDAP_SERVER=ldap://ldap:389
            - LDAP_BASE_DN=dc=inf,dc=ufes,dc=br
            - LDAP_USER=cn=admin,dc=inf,dc=ufes,dc=br
            - LDAP_PASSWORD=ldappw
            - BOCA_SYSTEM_USER=professorum
            - BOCA_ADMIN_USER=professordois
            ...
    ...
```

- Launch the application:

```sh
docker compose up --build
````

- Open a web browser and visit [http://localhost:8001/boca](http://localhost:8001/boca). Log in with the credentials of the user specified in the `BOCA_SYSTEM_USER` env variable (_professorum_). Then, create and activate a contest (via `Contest` menu);
- After being logged out, log in with the credentials of the user specified in the `BOCA_ADMIN_USER` env variable (_professordois_). Click on the `Users` menu, select the provided batch file and click on the `Import` button. Users _alunoum_, _alunodois_ and _alunotres_ should have been created;
- Finally, try to log with the credentials of a user that exists in the LDAP server (_alunoum_) and one that does not (_alunotres_)
- To stop the application

```sh
docker compose down
````
