### ISSUE TITLE
Admin password not taken into account when including new users

### ISSUE THREAD

**Issue by rlaiola** [AryelleSiqueira/boca-auth#8]
When logged in as admin (`BOCA_AUTH_METHOD=ldap`), under the user management page ([http://localhost:8001/boca/admin/user.php](http://localhost:8001/boca/admin/user.php)), the `Admin (this user) Password` field accepts anything (it can be empty, contain a wrong or the actual admin password). However, if `BOCA_AUTH_METHOD=password` the admin password is required. It would be nice to keep consistency here: either validate the password for all auth methods or, better, not doing so (the user is already logged in as admin!) and disabling/hiding the field on the UI.

<img width="1392" alt="Screen Shot 2023-09-19 at 08 04 07" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/22e2782e-dda5-4a13-be94-17d059f5e3a8">

**Proposed solution:**

<img width="1392" alt="Screen Shot 2023-09-19 at 08 20 56" src="https://github.com/AryelleSiqueira/boca-auth/assets/4059310/81251e72-f27e-4999-b74f-3eacb4962bc4">

Skipping password authentication in the backend (for all authentication methods) and hiding the UI field:

```css
<tr style="display: none;"> 
  <td width="35%" align="right">Admin (this user) Password:</td>
  <td width="65%">
    <input type="password" name="passwordo" value="" size="20" maxlength="200">
  </td>
</tr>
```

## How to reproduce this behavior?

- Edit the `docker-compose.yml` file accordingly:

```yaml
    ...
    boca-web:
        ...
        environment:
            ...
            - BOCA_AUTH_METHOD=ldap
            - LDAP_SERVER=ldap://ldap:389
            - LDAP_BASE_DN=dc=inf,dc=ufes,dc=br
            - LDAP_USER=cn=admin,dc=inf,dc=ufes,dc=br
            - LDAP_PASSWORD=ldappw
            - BOCA_SYSTEM_USER=professorum
            - BOCA_ADMIN_USER=professordois
            ...
    ...
```

- Launch the application:

```sh
docker compose up --build
````

- Open a web browser and visit [http://localhost:8001/boca](http://localhost:8001/boca). Log in with the credentials of the user specified in the `BOCA_SYSTEM_USER` env variable (_professorum_). Then, create and activate a contest (via `Contest` menu);
- After being logged out, log in with the credentials of the user specified in the `BOCA_ADMIN_USER` env variable (_professordois_). Click on the `Users` menu, fill in the form as indicated above and hit the `Send` button. In the `Admin (this user) Password` field try different options (leave it empty, type a wrong password and the correct one). All of them should work (the user is inserted anyway).
- To stop the application:
```sh
docker compose down
````
